export const LLEVA_COLORS = {

  brand: {
    blue:      '#007AFF',
    obsidian:  '#0A0A0A',
  },

  primary: {
    50:    '#E5F3FF',
    100:   '#CCE7FF',
    200:   '#99CFFF',
    300:   '#66B7FF',
    400:   '#339FFF',
    500:   '#007AFF',
    600:   '#0062CC',
    700:   '#004A99',
    800:   '#003166',
    900:   '#001933',
    950:   '#000D1A',
  },

  obsidian: {
    50:    '#F2F2F2',
    100:   '#E0E0E0',
    200:   '#BDBDBD',
    300:   '#9E9E9E',
    400:   '#757575',
    500:   '#616161',
    600:   '#424242',
    700:   '#212121',
    800:   '#141414',
    900:   '#0A0A0A',
    950:   '#050505',
  },

  semantic: {
    success:       '#34C759',
    successLight:  '#D4EDDA',
    successDark:   '#1E7E34',
    warning:      '#FF9500',
    warningLight: '#FFF3CD',
    warningDark:   '#856404',
    error:        '#FF3B30',
    errorLight:   '#FDECEA',
    errorDark:    '#B71C1C',
    info:        '#007AFF',
    infoLight:   '#E5F3FF',
    infoDark:    '#0062CC',
  },

  neutral: {
    0:     '#FFFFFF',
    50:    '#FAFAFA',
    100:   '#F5F5F5',
    200:   '#EEEEEE',
    300:   '#E0E0E0',
    400:   '#BDBDBD',
    500:   '#9E9E9E',
    600:   '#757575',
    700:   '#616161',
    800:   '#424242',
    900:   '#212121',
    950:   '#121212',
    1000:  '#000000',
  },

  tripStatus: {
    searching:   '#FF9500',
    matched:    '#007AFF',
    arriving:   '#AF52DE',
    in_progress: '#34C759',
    completed:  '#9E9E9E',
    cancelled:  '#FF3B30',
    disputed:   '#FF6B00',
  },

  driverStatus: {
    offline:   '#9E9E9E',
    online:    '#34C759',
    busy:      '#007AFF',
    suspended: '#FF3B30',
  },

  verificationStatus: {
    pending:   '#FF9500',
    in_review: '#007AFF',
    approved: '#34C759',
    rejected: '#FF3B30',
    expired:  '#9E9E9E',
  },

  surface: {
    background:     '#FFFFFF',
    backgroundAlt:  '#F5F5F5',
    card:           '#FFFFFF',
    cardAlt:        '#FAFAFA',
    border:         '#E0E0E0',
    borderFocus:    '#007AFF',
    divider:        '#EEEEEE',
    overlay:        'rgba(10, 10, 10, 0.5)',
    darkBackground: '#0A0A0A',
    darkBackgroundAlt: '#141414',
    darkCard:        '#1A1A1A',
    darkCardAlt:    '#212121',
    darkBorder:    '#2C2C2C',
    darkBorderFocus: '#007AFF',
    darkDivider:   '#1E1E1E',
  },

  text: {
    primary:     '#0A0A0A',
    secondary:   '#616161',
    tertiary:   '#9E9E9E',
    placeholder: '#BDBDBD',
    inverse:    '#FFFFFF',
    link:       '#007AFF',
    disabled:   '#BDBDBD',
    darkPrimary: '#FFFFFF',
    darkSecondary: '#BDBDBD',
    darkTertiary: '#757575',
    darkPlaceholder: '#616161',
    darkLink:   '#007AFF',
  },

} as const

export const LLEVA_COLORS_FLAT = {
  'brand-blue':      LLEVA_COLORS.brand.blue,
  'brand-obsidian':  LLEVA_COLORS.brand.obsidian,

  'primary-50':    LLEVA_COLORS.primary[50],
  'primary-100':   LLEVA_COLORS.primary[100],
  'primary-200':   LLEVA_COLORS.primary[200],
  'primary-300':   LLEVA_COLORS.primary[300],
  'primary-400':   LLEVA_COLORS.primary[400],
  'primary-500':   LLEVA_COLORS.primary[500],
  'primary-600':   LLEVA_COLORS.primary[600],
  'primary-700':   LLEVA_COLORS.primary[700],
  'primary-800':   LLEVA_COLORS.primary[800],
  'primary-900':   LLEVA_COLORS.primary[900],
  'primary-950':   LLEVA_COLORS.primary[950],

  'semantic-success':       LLEVA_COLORS.semantic.success,
  'semantic-success-light': LLEVA_COLORS.semantic.successLight,
  'semantic-success-dark': LLEVA_COLORS.semantic.successDark,
  'semantic-warning':      LLEVA_COLORS.semantic.warning,
  'semantic-warning-light': LLEVA_COLORS.semantic.warningLight,
  'semantic-warning-dark': LLEVA_COLORS.semantic.warningDark,
  'semantic-error':        LLEVA_COLORS.semantic.error,
  'semantic-error-light':  LLEVA_COLORS.semantic.errorLight,
  'semantic-error-dark':   LLEVA_COLORS.semantic.errorDark,
  'semantic-info':         LLEVA_COLORS.semantic.info,
  'semantic-info-light': LLEVA_COLORS.semantic.infoLight,
  'semantic-info-dark':  LLEVA_COLORS.semantic.infoDark,

  'neutral-0':   LLEVA_COLORS.neutral[0],
  'neutral-50':  LLEVA_COLORS.neutral[50],
  'neutral-100': LLEVA_COLORS.neutral[100],
  'neutral-200': LLEVA_COLORS.neutral[200],
  'neutral-300': LLEVA_COLORS.neutral[300],
  'neutral-400': LLEVA_COLORS.neutral[400],
  'neutral-500': LLEVA_COLORS.neutral[500],
  'neutral-600': LLEVA_COLORS.neutral[600],
  'neutral-700': LLEVA_COLORS.neutral[700],
  'neutral-800': LLEVA_COLORS.neutral[800],
  'neutral-900': LLEVA_COLORS.neutral[900],
  'neutral-950': LLEVA_COLORS.neutral[950],

  'surface-bg':          LLEVA_COLORS.surface.background,
  'surface-bg-alt':    LLEVA_COLORS.surface.backgroundAlt,
  'surface-card':      LLEVA_COLORS.surface.card,
  'surface-card-alt':  LLEVA_COLORS.surface.cardAlt,
  'surface-border':   LLEVA_COLORS.surface.border,
  'surface-border-focus': LLEVA_COLORS.surface.borderFocus,
  'surface-divider':   LLEVA_COLORS.surface.divider,
  'surface-dark-bg':   LLEVA_COLORS.surface.darkBackground,
  'surface-dark-card': LLEVA_COLORS.surface.darkCard,
  'surface-dark-border':LLEVA_COLORS.surface.darkBorder,

  'text-primary':      LLEVA_COLORS.text.primary,
  'text-secondary':   LLEVA_COLORS.text.secondary,
  'text-tertiary':   LLEVA_COLORS.text.tertiary,
  'text-placeholder': LLEVA_COLORS.text.placeholder,
  'text-inverse':   LLEVA_COLORS.text.inverse,
  'text-link':      LLEVA_COLORS.text.link,
  'text-disabled':  LLEVA_COLORS.text.disabled,

  'trip-searching':   LLEVA_COLORS.tripStatus.searching,
  'trip-matched':     LLEVA_COLORS.tripStatus.matched,
  'trip-arriving':    LLEVA_COLORS.tripStatus.arriving,
  'trip-progress':    LLEVA_COLORS.tripStatus.in_progress,
  'trip-completed':  LLEVA_COLORS.tripStatus.completed,
  'trip-cancelled': LLEVA_COLORS.tripStatus.cancelled,
  'trip-disputed':   LLEVA_COLORS.tripStatus.disputed,

  'driver-offline':   LLEVA_COLORS.driverStatus.offline,
  'driver-online':   LLEVA_COLORS.driverStatus.online,
  'driver-busy':     LLEVA_COLORS.driverStatus.busy,
  'driver-suspended':LLEVA_COLORS.driverStatus.suspended,

  'verification-pending':   LLEVA_COLORS.verificationStatus.pending,
  'verification-in-review': LLEVA_COLORS.verificationStatus.in_review,
  'verification-approved':  LLEVA_COLORS.verificationStatus.approved,
  'verification-rejected':  LLEVA_COLORS.verificationStatus.rejected,
  'verification-expired':   LLEVA_COLORS.verificationStatus.expired,
} as const

export const LLEVA_TYPOGRAPHY = {
  fontFamily: {
    sans:  ['Inter', 'SF Pro Display', 'system-ui', 'sans-serif'],
    mono:  ['JetBrains Mono', 'SF Mono', 'monospace'],
  },
  fontSize: {
    '2xs':  10,
    xs:     12,
    sm:     14,
    base:   16,
    lg:     18,
    xl:     20,
    '2xl':  24,
    '3xl':  30,
    '4xl':  36,
    '5xl':  48,
  },
  fontWeight: {
    regular:  '400' as const,
    medium:   '500' as const,
    semibold: '600' as const,
    bold:     '700' as const,
    black:    '900' as const,
  },
  lineHeight: {
    tight:   1.2,
    snug:    1.375,
    normal:  1.5,
    relaxed: 1.625,
  },
} as const

export const LLEVA_SPACING = {
  0:    0,
  px:    1,
  0.5:  2,
  1:    4,
  1.5:  6,
  2:    8,
  2.5:  10,
  3:    12,
  3.5:  14,
  4:    16,
  5:    20,
  6:    24,
  7:    28,
  8:    32,
  9:    36,
  10:   40,
  12:   48,
  14:   56,
  16:   64,
  20:   80,
  24:   96,
} as const

export const LLEVA_RADIUS = {
  none:   0,
  sm:     4,
  md:     8,
  lg:     12,
  xl:     16,
  '2xl':  20,
  '3xl':  24,
  full:   9999,
} as const

export const LLEVA_SHADOWS = {
  native: {
    sm: {
      shadowColor:   LLEVA_COLORS.brand.obsidian,
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.08,
      shadowRadius: 2,
      elevation:   2,
    },
    md: {
      shadowColor:   LLEVA_COLORS.brand.obsidian,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.10,
      shadowRadius: 8,
      elevation:   4,
    },
    lg: {
      shadowColor:   LLEVA_COLORS.brand.obsidian,
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.12,
      shadowRadius: 16,
      elevation:   8,
    },
  },
  web: {
    sm:  '0 1px 2px 0 rgba(10, 10, 10, 0.08)',
    md:  '0 4px 8px 0 rgba(10, 10, 10, 0.10)',
    lg:  '0 8px 16px 0 rgba(10, 10, 10, 0.12)',
    xl:  '0 16px 32px 0 rgba(10, 10, 10, 0.14)',
  },
} as const

export const LLEVA_ANIMATION = {
  duration: {
    instant: 0,
    fast:   150,
    normal: 250,
    slow:   400,
  },
  easing: {
    standard:   'cubic-bezier(0.4, 0, 0.2, 1)',
    decelerate: 'cubic-bezier(0, 0, 0.2, 1)',
    accelerate: 'cubic-bezier(0.4, 0, 1, 1)',
    spring:    'cubic-bezier(0.175, 0.885, 0.32, 1.275)',
  },
} as const

export type LlevaColorToken = keyof typeof LLEVA_COLORS_FLAT